apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-casbin
  labels:
    app: go-casbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-casbin
  template:
    metadata:
      labels:
        app: go-casbin
    spec:
      containers:
      - name: go-casbin
        image: go-casbin:latest
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-casbin-service
spec:
  selector:
    app: go-casbin
  ports:
  - port: 80
    targetPort: 9000
  type: ClusterIP 

---
# 需要额外的Ingress配置
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-casbin-ingress
spec:
  rules:
  - host: go-casbin.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-casbin-service
            port:
              number: 30000