version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: scripts/dockerfile.dev
    container_name: gim-app
    ports:
      - "90000:90000"
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go
    environment:
      - NODE_ENV=development
    restart: unless-stopped
