# 编译阶段
FROM golang:1.24-alpine AS builder

WORKDIR /app

# 安装依赖工具
RUN apk add --no-cache git

# 拷贝 go.mod 和 go.sum 以缓存依赖
COPY go.mod go.sum ./
RUN go mod download

# 拷贝源码并编译
COPY . .
RUN go build -o main .

# 运行阶段（更小的镜像）
FROM alpine:latest

WORKDIR /app

# 拷贝编译好的二进制文件
COPY --from=builder /app/main .

# 配置环境变量（如有）
ENV GIN_MODE=release

EXPOSE 90000

CMD ["./main"]